### PR TITLE
Add declarative as syntax

### PR DESCRIPTION
**Pull request by miciek**
I thought about moving `as` syntax before the interpretation phase and come up with something like that. There is an alternative approach that is based on creating a new operation in algebra (decodeAs) and decoding as interpretation step.

Any thoughts @pepegar?

### CODE REVIEW

**Comment by pepegar** [comment]
Hi @miciek!

First of all, thanks for the contribution, I also had in mind something like this.

However, I think it's better to use `Either[CodecException, T]` as the intermeditate representation instead of `HttpResponseToDecode[T]`.

How I imagine is:

`Free[HttpRequestF, HttpResponse] -> Free[HttpRequestF, Either[CodecException, T]] -> F[T]`

What do you think? Do you think it's OK to change it to `Either`?

Also, on the weekend I've been working in the integration with `cats-effect`.  The cool thing about cats-effect is that it has specialized typeclasses for effects, and I changed all `MonadError[Throwable, F]` restrictions to `Sync[F]`, which inherits from `MonadError` but provides more fine-grained effect handling.

**Comment by pepegar** [comment]
Hey @miciek , This has been open for a long time now. I think I've come up with a solution for this that will allow an easier integration and a cleaner API.

What I propose is creating a `MarshallF[A]` algebra, that will allow marshalling `A` to an `Entity`, and unmarshall `Entity`es to `A`. Then we'll be able to model marshallers and unmarshallers to, for example `HttpRequest` and `HttpResponse` using `map` & `contramap` operations on the marshaller.

What do you think?

I'm planning to integrate that this week in Hammock to be able to release `0.8` before new years.

**Comment by miciek** [comment]
Sounds cool @pepegar Do you want to me implement that or do you already have something and we need to close this PR?

**Comment by pepegar** [comment]
I think we can safely close this, as I'll work on a different implementation.

**Pull request closed without merging**
